sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t muralikrishna1488/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true muralikrishna1488/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ca-central-1'
  app: 'Docker-React-Travis Integration Check'
  env: 'travistesting'
  bucket_name: 'elasticbeanstalk-ca-central-1-088993821011'
  bucket_path: 'Docker-React-Travis Integration Check'
  on:
    all_branches: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
