sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t muralikrishna1488/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true muralikrishna1488/docker-react npm run test
git 